### ISSUE TITLE
Footer clings to body between 1150-1425px

### ISSUE THREAD

**Issue by tlambert03** [napari/napari-sphinx-theme#89]
<img width="1305" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/158494816-d621bee4-f5a2-46cb-bd32-d977f85e4dba.png">

**Comment by codemonkey800** [comment]
This should be fixed in https://github.com/napari/napari-sphinx-theme/releases/tag/v0.1.0, could you check again please? 😄 We may have to redeploy because I just released today

**Comment by tlambert03** [comment]
still there on https://napari.org/usage.html ... will check tomorrow of after next docs deploy

**Comment by jni** [comment]
Note that deploy docs can be manually triggered by maintainers here:

https://github.com/napari/napari/actions/workflows/deploy_docs.yml

Just triggered a build, can't wait any longer, anticipation is killing me :joy:

**Comment by jni** [comment]
Well, it's not clinging anymore (if I understand the issue correctly), but something funky still going on...

https://user-images.githubusercontent.com/492549/159397117-974f695a-fe98-47d8-ba79-1158ac806d48.mov

This is FF 97.0.1 on macOS 11.4. I presume the "correct" behavior is that the footer bar should align exactly (no scrolling) with the bottom of the window if it fits?

**Comment by codemonkey800** [comment]
hmm, i probably need to do some CSS calculations for the height then because this is a seemingly standard way of pushing the footer to the bottom: https://stackoverflow.com/questions/4575826/how-to-push-a-footer-to-the-bottom-of-page-when-content-is-short-or-missing

but the side effect is, as you've found, that the footer is pushed past the viewport and requires scrolling. i'll see what can be done, maybe doing something like `calc(100vh - footer-height)` will work

**Comment by psobolewskiPhD** [comment]
The disappearing footer is fixed with #134
